---
- name: Converge
  hosts: all

  roles:
    - role: boutetnico.logstash
      logstash_plugins:
        - name: logstash-input-github
          version: 3.0.11
        - name: logstash-filter-dissect
