---
- name: Converge
  hosts: all

  roles:
    - role: ansible-role-logstash
      logstash_plugins:
        - name: logstash-input-github
          version: 3.0.8
        - name: logstash-filter-dissect
